name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install cppcheck
      run: sudo apt-get install -y cppcheck
      
    - name: Run cppcheck
      run: cppcheck --enable=all --std=c++17 --suppress=missingIncludeSystem --error-exitcode=1 src/ include/
  
  clang-format:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install clang-format
      run: sudo apt-get install -y clang-format
      
    - name: Check code formatting
      run: |
        find src include tests -name "*.cpp" -o -name "*.h" | xargs clang-format -style=file -n -Werror 