name: Multi-Platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        build_type: [Release, Debug]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libcurl4-openssl-dev nlohmann-json3-dev
    
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install cmake curl nlohmann-json
    
    - name: Create build directory
      run: mkdir -p build
      
    - name: Configure CMake
      run: cd build && cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      
    - name: Build
      run: cd build && cmake --build . --config ${{ matrix.build_type }} 